// Copyright 2025 Notedown Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"html/template"
	"log"
	"os"
	"strings"
)

func main() {
	dict, err := os.ReadFile("generate/dict.txt")
	if err != nil {
		log.Fatal(err)
	}
	words := strings.Split(string(dict), "\n")

	tmpl, err := template.New("words").Parse(templateTxt)
	if err != nil {
		log.Fatal(err)
	}

	f, err := os.Create("dict.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, words); err != nil {
		log.Fatal(err)
	}
}

const templateTxt = `// Code generated by go generate; DO NOT EDIT.
package words

var dict = []string{
{{- range .}}
    "{{.}}",
{{- end}}
}`
