name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: make hygiene
    - run: make dirty
  
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, functional]
    name: ${{ matrix.test-type }} tests
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    # Run tests based on matrix
    - name: Run unit tests
      if: matrix.test-type == 'unit'
      run: make test-unit

    - name: Run functional tests  
      if: matrix.test-type == 'functional'
      run: make test-functional
